### PR TITLE
Add feature "discard warning message for specific language" and test it.

### PR DESCRIPTION
**Pull request by eregnier**
related to the issue 
https://github.com/Polyconseil/vue-gettext/issues/61 
and 
https://github.com/Polyconseil/vue-gettext/issues/60#issuecomment-358696996

### CODE REVIEW

**Comment by kemar** [comment]
Thanx :)

But can you please remove the files in the `dist` dir ? https://github.com/Polyconseil/vue-gettext/blob/master/README_DEV.md#pull-request-guidelines

**Comment by eregnier** [comment]
This is done. Sorry for the mistake :)

**Comment by kemar** [comment]
Don't forget to push your changes ;)

**Comment by eregnier** [comment]
This is also done, I amended my commit and push forced it , so you may use the commit submited with this PR. Check de diff !

**Comment by kemar** [comment]
I can still see the files in `dist` => https://github.com/Polyconseil/vue-gettext/pull/62/files#diff-bcbe09dcb9ae50571f8ae3ffac467790

**Comment by eregnier** [comment]
I seems to be good now. Is it ok on your side too ?

**Comment by kemar** [comment]
Yup, thanx :)

**Comment by kemar** [comment]
Thanx @eregnier, I published a new release with your code https://github.com/Polyconseil/vue-gettext/releases/tag/v2.0.26

**Pull request merged**
