### PR TITLE
Trim whitespaces in `msgid`

### PR DESCRIPTION
**Pull request by hauleth**
This sometimes prevent translations in cases like:

    <div v-translate>
        Test
    </div>

And while `easygettext` omit whitespaces in this situation it causes
problems.

### CODE REVIEW

**Comment by kemar** [comment]
Thank you.

But please, can you follow the [Pull request guidelines](https://github.com/Polyconseil/vue-gettext/blob/master/README_DEV.md#pull-request-guidelines) and at least remove files in `dist` because they are automatically generated at release time?

**Comment by hauleth** [comment]
@kemar updated

**Comment by kemar** [comment]
Thank you very much, your tests are very helpful.

As noted [above your change](https://github.com/Polyconseil/vue-gettext/pull/65/files#diff-c4447b04d8f41855d00d9e821c25ed7cR71), not trimming is done on purpose.

Looking at your tests, it looks that there is a problem with the `tab` character since the other tests are OK with the current code in master.

I'm looking at it.

**Comment by hauleth** [comment]
@kemar the problem is that `easygettext` trims entries, so:

    <translate>Foo </translate>

And

    <translate>Foo</translate>

Are the same for `easygettext` while being different for `vue-gettext`.

**Comment by kemar** [comment]
Yes, the problem is known since issue #15. But it's [already solved](https://github.com/Polyconseil/vue-gettext/blob/d9b77461f7f0fa0216f8f69e2a0c7564b0b5491f/src/translate.js#L45-L54) for spaces with a little bit of a hack, see #38.

This is not only a problem with `easygettext` but also with [Vue's `_renderChildren`](https://github.com/Polyconseil/vue-gettext/blob/4004bda2097c8635dd3259e2d29708e670035b64/src/component.js#L19-L21).

@vperron I understand why `easygettext` trims the templates and I think that there is no straightforward answer.

@hauleth you only have a problem when you use `tab`s and I think that this is not a bug.

**Comment by kemar** [comment]
Thank you @hauleth, I just [released a patch](https://github.com/Polyconseil/vue-gettext/releases/tag/v2.0.29) for your problem. I'm closing this issue now.

You were right because `msgid` was not trimmed consistently.

Your problem should be solved.

**Comment by vperron** [comment]
:tada:

**Comment by kemar** [comment]
@vperron after having read [*When does white space matter in HTML?*](https://medium.com/@patrickbrosset/when-does-white-space-matter-in-html-b90e8a7cdd33), I'm still thinking about your comment:

> To me the problem is more in easygettext where we should either not trim (never) or have an option to do so.

Maybe you're right, because sometimes the purpose of a webdesigner may be to respect `{ white-space: pre; }` so the spaces should not be trimmed.

Anyway, maybe let's wait for someone to encounter the problem :)

**Pull request closed without merging**
