### PR TITLE
Added support for dot notation during interpolation

### PR DESCRIPTION
**Pull request by lauritzen**

### CODE REVIEW

**Comment by kemar** [comment]
Hello @lauritzen and thank you for your pull request!

However I'm not going to merge it in this state.

I have not specified how to contribute to `vue-gettext` but I will clarify the *Pull Request Guidelines* in the future [as Vue does](https://github.com/vuejs/vue/blob/299ecfc19fa0f59effef71d24686bd7eb70ecbab/.github/CONTRIBUTING.md#pull-request-guidelines).

It would be great if you could:

- explain why you are adding this feature in the PR description, so I can quickly understand what you want
- add *at least* 1 accompanying test case, [look here for `interpolate`](https://github.com/Polyconseil/vue-gettext/blob/080a8e86aec524184c754b3fe6a9972fd8f55ad4/test/specs/interpolate.spec.js)
- make sure `npm test` passes
- make sure `node_modules/.bin/eslint src test dev build` passes
- not touch files in `dist` because they are automatically generated at release time, you can remove them :)

**Comment by lauritzen** [comment]
Very understandable, actually thought about putting in a test just after submitting the pull request. The project I'm working on has a pretty tight schedule, but I'll see if I can find some time to touch up the pull request.

**Comment by kemar** [comment]
@lauritzen yup I understand. Just give me an example of your context and I'll work on it. I guess it's something like this:

```
let context = {
    foo: {
        bar: 'baz',
    }
}
```

Btw, I added some [PR guidelines here](https://github.com/Polyconseil/vue-gettext/blob/178b5d0d5e000825dea9fb330d8cc64b4c2f4738/README_DEV.md#pull-request-guidelines).

**Comment by lauritzen** [comment]
Great! Exactly. So in the template: `<translate>%{ foo.bar }</translate>` equals `baz`.

**Comment by kemar** [comment]
This should be fixed now in https://github.com/Polyconseil/vue-gettext/releases/tag/v2.0.6

**Pull request closed without merging**
